JavaAssignment/src/purva/HelloWorld_Purva.java
Created class for printing Hello World
=> Adding 1 file for Hello World

JavaAssignment/src/rahulM/Hello_RahulM.java
Hi Please review and approve TIA.
=> Adding hello file

JavaAssignment/src/monali/HelloMonali.java
=> First Git Code : Monali

JavaAssignment/src/soumya/TestCheck.java
Changed print message to hello world
=> Hello world java file

JavaAssignment/src/shashank/HelloWorldShashank.java
First program of printing hello.
=> First git wala program

JavaAssignment/src/arpit/HelloClass.java, JavaAssignment/src/arpit/TestCheck.java, JavaAssignment/src/technoCredits/Assignment1_Q1.java
updated package name & adding one java file.
=> updated package name & adding one java file.

JavaAssignment/src/purva/q7TimeConversion.java
=> Assignment1_Q7_Purva

JavaAssignment/src/soumya/TimeConverter_Client.java, JavaAssignment/src/soumya/TimeConverter_Service.java
=> Assignment_Q7_Soumya

JavaAssignment/src/soumya/PrimeNumber_Client.java, JavaAssignment/src/soumya/PrimeNumber_Service.java
=> Assignment_Q10_Soumya

JavaAssignment/src/purva/q4_Client.java, JavaAssignment/src/purva/q4_Service.java
=> Assignment1_Q4_Purva

JavaAssignment/src/soumya/TempConverter_Client.java, JavaAssignment/src/soumya/TempConverter_Service.java
=> Assignment_Q6_Soumya

JavaAssignment/src/purva/SwapNoTemp.java
=> Assignment1_Q9_Purva

JavaAssignment/src/soumya/Student_Client.java, JavaAssignment/src/soumya/Student_Service.java
=> Assignment_Q2_Soumya

JavaAssignment/src/purva/SumPrimeNos.java
=> Assignment1_Q10_Purva

JavaAssignment/src/soumya/Calculation_Client.java, JavaAssignment/src/soumya/Calculation_Service.java
=> Assignment_Q1_Soumya

JavaAssignment/src/soumya/InterestCalculation_Service.java, JavaAssignment/src/soumya/InteretCalculationClient.java, JavaAssignment/src/soumya/SwapWith_Client.java, JavaAssignment/src/soumya/SwapWith_Service.java
=> Assignment Q5 soumya

JavaAssignment/src/soumya/SwapWith_Client.java, JavaAssignment/src/soumya/SwapWith_Service.java
=> Assignment_Q8_Soumya

JavaAssignment/src/monali/SumPrimeNo.java
Prime numbers addition program is completed
=> Assignment1_Q10_Monali

JavaAssignment/src/soumya/SwapWithout_Client.java, JavaAssignment/src/soumya/SwapWithout_Service.java
=> Assignment_Q9_Soumya

JavaAssignment/src/purva/q8_SwapTemp.java
=> Assignment1_Q8_Purva

JavaAssignment/src/purva/q6TempConv.java
=> Assignment1_Q6_Purva

JavaAssignment/src/purva/q5_SimpleInterest.java
=> Assignment1_Q5_Purva

JavaAssignment/src/monali/SwappingWithoutThirdVar.java
Swapping of two number without using third variable completed
=> Assignment1_Q9_Monali

JavaAssignment/src/monali/SwapByThirdVar.java
Swapping of two number using third variable completed
=> Assignment_Q8_Monali

JavaAssignment/src/monali/SecToMinToHour.java
Seconds conversion program is completed.
=> Assignment Q7 Completed Monali

JavaAssignment/src/monali/FarhToCelsius.java
Fahrenheit to Celsius program is completed
=> Assignment_Q6_Monali

JavaAssignment/src/purva/q2Client.java, JavaAssignment/src/purva/q2Service.java
=> Assignment1_Q2_Purva

JavaAssignment/src/monali/Q5_SimpleInterest.java
=> Fifth Question completed Monali

JavaAssignment/src/monali/Q2_StudentClass.java
Second Question Completed Monali
=> Second Question Completed Monali

JavaAssignment/src/monali/Q1_Mona.java
=> Completed First Question_Monali

JavaAssignment/src/purva/MathsOperationsClient_Purva_Q1.java, JavaAssignment/src/purva/MathsOperations_Purva_Q1.java
This request for question 1 contains 2 programs. 1 is client class and other is service class
"MathsOperationsClient_Purva_Q1"is client class which is calling all services or math operations written in service class "MathsOperations_Purva_Q1"
=> Adding 2 files for question 1 from assignment

JavaAssignment/src/purva/q3SquareCube.java
=> Assignment1_Q3_Purva

JavaAssignment/src/arpit/AreaQ2.java, JavaAssignment/src/arpit/MeetingRoomQ1.java
Overloading concept assignment completed.
=> Arpit set3 assignment3

JavaAssignment/src/arpit/AdditionQ6.java, JavaAssignment/src/arpit/BookQ5.java, JavaAssignment/src/arpit/CircleQ1.java, JavaAssignment/src/arpit/ClientCircleQ1.java, JavaAssignment/src/arpit/EmployeeQ3.java, JavaAssignment/src/arpit/EmployeeQ7.java, JavaAssignment/src/arpit/SquareQ4.java, JavaAssignment/src/arpit/TestBookQ5.java, JavaAssignment/src/arpit/TestEmployeeQ3.java, JavaAssignment/src/arpit/TestEmployeeQ7.java, JavaAssignment/src/arpit/TestSquareQ4.java
Classes and Objects Q1_Q3_Q4_Q5_Q6_Q7 completed.
=> Arpit set2 assignment3

JavaAssignment/src/purva/PurvaAssign3_Calculator_q4_Client.java, JavaAssignment/src/purva/PurvaAssign3_Calculator_q4_Service.java, JavaAssignment/src/purva/PurvaAssign3_InputOutput.java, JavaAssignment/src/purva/PurvaAssign3_JDM_q1.java, JavaAssignment/src/purva/PurvaAssign3_JDM_q2.java, JavaAssignment/src/purva/PurvaAssign3_JDM_q3.java, JavaAssignment/src/purva/PurvaAssign3_JDM_q6_Marks.java, JavaAssignment/src/purva/PurvaAssign3_JDM_q7_Area.java, JavaAssignment/src/purva/PurvaAssign3_JDM_q7_AreaService.java, JavaAssignment/src/purva/PurvaAssign3_q5_Weekdays.java
This PR contains 7 programs from Java Decision Making & Switch case section
=> Purva_Assignment 3_JDM & Switch Case

JavaAssignment/src/arpit/CalculateAreaQ7.java, JavaAssignment/src/arpit/CalculatorUsingSwitchQ4.java, JavaAssignment/src/arpit/CheckStudentsResultQ6.java, JavaAssignment/src/arpit/DisplayWeekdaysQ5.java, JavaAssignment/src/arpit/GreaterNumberUsingTernaryOperator.java, JavaAssignment/src/arpit/InputOutputOperations.java, JavaAssignment/src/arpit/LargestNumberUsingLogicalAnd.java, JavaAssignment/src/arpit/LeapYearOrNonLeapYear.java, JavaAssignment/src/arpit/TestAreaQ7.java
Decision Making and Switch case questions completed.
=> Arpit set1 assignment3

JavaAssignment/src/soumya/AddTest.java, JavaAssignment/src/soumya/Addition.java, JavaAssignment/src/soumya/Area_Client.java, JavaAssignment/src/soumya/Area_Service.java, JavaAssignment/src/soumya/Bank.java, JavaAssignment/src/soumya/BankClient.java, JavaAssignment/src/soumya/Book.java, JavaAssignment/src/soumya/BookTest.java, JavaAssignment/src/soumya/Calculator_Client.java, JavaAssignment/src/soumya/Calculator_Service.java, JavaAssignment/src/soumya/Circle.java, JavaAssignment/src/soumya/ClientCircle.java, JavaAssignment/src/soumya/Employee.java, JavaAssignment/src/soumya/EmployeeQ7.java, JavaAssignment/src/soumya/EmployeeQ7Test.java, JavaAssignment/src/soumya/GreaterNumTernary_Client.java, JavaAssignment/src/soumya/GreaterNumTernary_Service.java, JavaAssignment/src/soumya/LargeNumLogical_Client.java, JavaAssignment/src/soumya/LargeNumLogical_Service.java, JavaAssignment/src/soumya/LeapYear_Client.java, JavaAssignment/src/soumya/LeapYear_Service.java, JavaAssignment/src/soumya/Square.java, JavaAssignment/src/soumya/StudentMarks_Client.java, JavaAssignment/src/soumya/StudentMarks_Service.java, JavaAssignment/src/soumya/TestEmployee.java, JavaAssignment/src/soumya/TestSquareClass.java, JavaAssignment/src/soumya/Weekday_Client.java, JavaAssignment/src/soumya/Weekday_Service.java
Assignment3_Q1_Q2_Q3_Q4_Q5_Q6_Q7
=> Assignment3_Q1_Q2_Q3_Q4_Q5_Q6_Q7

JavaAssignment/src/soumya/CheckNo_Client.java, JavaAssignment/src/soumya/CheckNo_Service.java, JavaAssignment/src/soumya/MaxMin_Client.java, JavaAssignment/src/soumya/MaxMin_Service.java, JavaAssignment/src/soumya/MissingNumber_Client.java, JavaAssignment/src/soumya/MissingNumber_Service.java, JavaAssignment/src/soumya/SecLarge_Client.java, JavaAssignment/src/soumya/Seclarge_Service.java, JavaAssignment/src/soumya/SumEqual_Client.java, JavaAssignment/src/soumya/SumEqual_Service.java
Assignment_Q1_Q3_Q4_Q5_Q7_Soumya
=> Assignment_Que_Set2_Soumya

JavaAssignment/src/purva/InputOutput.java, JavaAssignment/src/purva/PurvaAssignment2LinearMissNo.java, JavaAssignment/src/purva/PurvaAssignment2Q1.java, JavaAssignment/src/purva/PurvaAssignment2Q10.java, JavaAssignment/src/purva/PurvaAssignment2Q2.java, JavaAssignment/src/purva/PurvaAssignment2Q3.java, JavaAssignment/src/purva/PurvaAssignment2Q4.java, JavaAssignment/src/purva/PurvaAssignment2Q5.java, JavaAssignment/src/purva/PurvaAssignment2Q6.java, JavaAssignment/src/purva/PurvaAssignment2Q7.java, JavaAssignment/src/purva/PurvaAssignment2Q8.java, JavaAssignment/src/purva/PurvaAssignment2Q9.java, JavaAssignment/src/purva/PurvaAssignment2TreeCount.java
Purva_Assignment2_Array:
This PR has 10 array program+ 1 program InputOutput.java which is used by all programs for accepting array input for user, Other 2 programs are - tree visible program and linear series missing program.
=> Purva_Assignment2_Array

JavaAssignment/src/monali/DifferIndexInArray.java, JavaAssignment/src/monali/DuplicateNumber.java, JavaAssignment/src/monali/EqualityOfTwoArray.java, JavaAssignment/src/monali/FirstDifferIndex.java, JavaAssignment/src/monali/InputOutputArrayInt.java, JavaAssignment/src/monali/LargestSmallest.java, JavaAssignment/src/monali/MaxDifferIndex.java, JavaAssignment/src/monali/MissingNoLinearSeries1to10.java, JavaAssignment/src/monali/PresenceOfNumber.java, JavaAssignment/src/monali/SecondLargestNo.java, JavaAssignment/src/monali/SumEqualToNumbers.java
Array 6 program completed remaining 4 will create new branch
=> Array Assignment 6 programs completed

JavaAssignment/src/arpit/MaxValueAtDifferIndexQ10.java
=> Arpit_ArrayQ10

JavaAssignment/src/shashank/CountOfTrees.java, JavaAssignment/src/shashank/DuplicateNumSearch.java, JavaAssignment/src/shashank/LinearSeriesMiss.java, JavaAssignment/src/shashank/UserInputArrayInt.java
Program to print visible trees count
Program to find duplicate number in a series
Program to find missing number in a series
=> Assignment 26th Jan
